# Generated by Django 3.2.13 on 2022-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('published_date', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50, null=True)),
                ('average_rating', models.CharField(max_length=50, null=True)),
                ('ratings_count', models.CharField(max_length=50, null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
